### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/FlatUI#13]
Cкинь пожалуйста скрин макета с наложенным PerfectPixel (желательно в инверсии) и открытым окошком настроек

**Comment by DenisKhodasevich** [comment]
![screenshot-localhost_8080-2020 02 05-02_26_02](https://user-images.githubusercontent.com/43818614/73789331-6743a200-47c0-11ea-9da6-ad4323d424fa.png)
Пытался максимально всё выровнять, но не везде получилось, потому что макет кривой местами. В секции PERCENTAGES / PIE CHART расстояние между каждой диаграммой разное. У слайдера со шкалой расположение цифр не соответствует тому, как на самом деле будет перемещаться ручка по этим делениям. Заголовок TOGGLES немного выше, чем элементы слева, с которыми он, вроде бы, должен быть на одном уровне. Чекбоксы смещены немного влево от центра, как и заголовки USER PROFILE и MESSAGING.

**Comment by Nelliza** [comment]
По сути меня только **toggles** смущает, на остальное думаю можно забить )

**Comment by DenisKhodasevich** [comment]
![FireShot Capture 001 - UI Kit - localhost](https://user-images.githubusercontent.com/43818614/74251923-b2a10780-4d0e-11ea-8888-a2ccd3cffa87.png)
Поправил
