### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/FlatUI#2]
**dropdown.scss**
![1](https://user-images.githubusercontent.com/19621113/71556803-cee23100-2a4d-11ea-8377-36724ddb1d53.png)

В стилевых файлах мы используем везде одинарные кавычки, исправь плиз

**Comment by Nelliza** [comment]
**events.pug**
![1](https://user-images.githubusercontent.com/19621113/72527366-ae054280-3879-11ea-8515-5c44e8555e47.png)
Для таких случаев предусмотрена короткая форма записи для упрощения кода:
вместо `link: link` ты можешь написать просто `link`.
При этом сокращенные записи свойств, согласно [стайлгайду от Airbnb](https://github.com/leonidlebedev/javascript-airbnb#objects--grouped-shorthand), указываются первыми при объявлении объекта

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/74100926-2a233b00-4b45-11ea-99e3-cff9c7154680.png)
А почему именно так? )

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/74100926-2a233b00-4b45-11ea-99e3-cff9c7154680.png)
А почему именно так? )

**Comment by DenisKhodasevich** [comment]
Переписал на более очевидное условие)
