### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by Nelliza** [DenisKhodasevich/FlatUI#5]
![1](https://user-images.githubusercontent.com/19621113/72046327-3eb3af80-32c9-11ea-9e03-f57c0ca477dc.gif)

По завершении обработки клика фоновый цвет кнопки не возвращается к исходному

**Comment by DenisKhodasevich** [comment]
Так происходит из-за того, что при клике происходит фокусирование на элементе, а в стандартах написано, что если пишешь в стилях элемента outline: none, то нужно написать другие стили, которые будут применяться к элементу при фокусировании на нём. Я пробовал делать отключение фокуса при клике, но в таком случае фокусировка исчезает даже тогда, когда нажимаешь на кнопку пробелом, в итоге нельзя нажать на кнопку пробелом повторно, а это иногда может быть полезно. Пробовал оставлять outline, но в этом нет смысла, потому что его почти не видно, а  увеличить в размере не получится из-за того, что у standard-button прописано overflow: hidden, что необходимо для того, чтобы круг, появляющийся при клике, не выходил за рамки кнопки. Можно, конечно, менять стили при клике с помощью js, но тогда будет не видно, на каком элементе сейчас фокус, а в стандартах написано, что сфокусированный элемент должен быть выделен. Поэтому я не вижу смысла тут что-либо менять.

**Comment by DenisKhodasevich** [comment]
Так происходит из-за того, что при клике происходит фокусирование на элементе, а в стандартах написано, что если пишешь в стилях элемента outline: none, то нужно написать другие стили для :focus этому элементу. Выделить кнопку с помощью outline не получится, потому что у неё уже есть border. Других способов выделить кнопку, на которой происходит фокусирование, кроме как оставить всё как есть, я не вижу, поэтому я удалил коммит к этому ишью и связанные с ним изменения.

**Comment by DenisKhodasevich** [comment]
Так происходит из-за того, что при клике происходит фокусирование на элементе, а в стандартах написано, что если пишешь в стилях элемента outline: none, то нужно написать другие стили для :focus этому элементу. Если оставить outline или добавить box-shadow для :focus, то их не будет заметно из-за того, что в стилях standard-button написано overflow-hidden, что нужно для того, чтобы круг, появляющийся при клике, не выходил за рамки кнопки. Как тогда ещё можно выделить сфокусированную кнопку?

**Comment by Nelliza** [comment]
Предлагаю выделить ее при фокусе более темной рамкой внизу, но без окрашенного фона
